import localFont from "next/font/local";
import "../globals.css";
import NavBar from "@/components/navBar/NavBar";
import Footer from "@/components/footer/Footer";

import { notFound } from 'next/navigation';
import { getMessages } from 'next-intl/server';
import {NextIntlClientProvider} from "next-intl"
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout  ({ children, params: { locale }}) {
 
  
  const messages = await getMessages();
  // if(!locale || !messages[locale]) notFound();
  

  return (
    
    <html lang={locale} >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <NextIntlClientProvider timeZone="Europe/Vienna"  locale={locale} messages={messages} >
        <NavBar/>
        {children}
        <Footer/>
      </NextIntlClientProvider>
      </body>
    </html>
  );
}
